### PR TITLE
feat: replace reload prompt with button in app bar

### PR DESCRIPTION
**Pull request by lukashass**
"Update" sounds less scary.

### CODE REVIEW

**Comment by anbraten** [comment]
@lukashass Maybe having it as a button as part of the app-bar instead of the popup would be nice as well. 

image

**Comment by lukashass** [comment]
image

@anbraten Good idea. Like this?

**Comment by anbraten** [comment]
@lukashass Pretty nice already. Some more ideas: I would stick to a download icon as it is an app and reloading looks like "reloading data / bus arrivals" to me. In addition should we only show an icon on mobile as the button is pretty larger otherwise.

**Comment by lukashass** [comment]
@anbraten Changed to a cloud icon. I would like to leave the text though, as there is still plenty of space left.

**Review by anbraten — APPROVED** [review]

**Pull request merged**
