### PR TITLE
feat: add bus location to trip line

### PR DESCRIPTION
**Pull request by lukashass**

### CODE REVIEW

**Comment by anbraten** [comment]
@lukashass Could you provide a screenshot?

**Comment by lukashass** [comment]
@anbraten That was fast :sweat_smile: 

image

**Comment by anbraten** [comment]
@lukashass Sure. Still not 100% getting the change. So previously the stop a bus is currently at was missing?

**Comment by lukashass** [comment]
@anbraten Yes. Before:

image

**Review by anbraten — APPROVED** [review]

**Pull request merged**
